### PR TITLE
input-field: fail display improvments

### LINKED ISSUE #97: Cant see if i typed wrong the password
When we type the password wrong, it would be cool to see a error like a red msg or maybe a moving animation that the password is incorect, rn its just stays like that when i typed the wrong pass, and idk what just happened, like, its frozen or what? then i need to type it again. Its not a big of a deal but it would be a nice feature

### LINKED ISSUE #144: [BUG]`fade_on_empty = true` doesn't give the input field a shadow
Basically what it says in the title. If a shadow is configured for the input field, but the input field is configured to fade away when it's empty, there will be no shadow around the input field. Simply allowing the input field to be there all the time fixes it.

Config file [here](https://github.com/Andy3153/hyprland-rice/blob/master/dotconfig/hypr/hyprlock.conf):
```conf
# vim: set fenc=utf-8 ts=4 sw=0 sts=0 sr et si tw=0 fdm=marker fmr={{{,}}}:

# {{{ Variables
# {{{ Colors
# {{{ Colorscheme
source = ~/.config/hypr/colorschemes/catpucchin-mocha.conf
# }}}

# {{{ Generic
$font        = $text
$font_splash = $subtext0
$bg          = $base
$select      = $blue
# }}}
# }}}
# }}}

# {{{ General
general {
    grace = 10
}
# }}}

# {{{ Background
background {
    monitor =
    color   = rgb($bg)
    path    = /home/andy3153h/.local/share/wallpaper-lock.png #screenshot

    # {{{ Blur
    #size              = 7
    #passes            = 2
    #noise             = 0.01
    #
    #contrast          = 1 #0.9
    #brightness        = 1 #0.8
    #vibrancy          = 0 #0.17
    #vibrancy_darkness = 0 #0.0
    # }}}
}
# }}}

# {{{ Password field
input-field {
    monitor           =
    fade_on_empty     = true
    fade_timeout      = 1000
    hide_input        = false
    placeholder_text  =

    position          = 0, -50
    halign            = center
    valign            = center

    size              = 250, 50
    dots_size         = 0.1
    dots_spacing      = 0.3
    dots_center       = true

    rounding          = -1

    outline_thickness = 2

    inner_color       = rgb($bg)
    outer_color       = rgb($select)
    font_color        = rgb($font)
    shadow_color      = rgb($base)

    shadow_passes     = 2
    shadow_size       = 5
    shadow_boost      = 1.2
}
# }}}

# {{{ Time
label {
    monitor       =
    text          = $TIME
    font_size     = 70
    font_family   = Cantarell

    color         = rgb($font)
    shadow_color  = rgb($base)

    shadow_passes = 2
    hsadow_size   = 5
    shadow_boost  = 1.2

    position      = 0, 350
    halign        = center
    valign        = center
}
# }}}

# {{{ Date
label {
    monitor       =
    text          = cmd[update:1000] date "+%A, %d %B %Y"
    font_size     = 25
    font_family   = Cantarell

    color         = rgb($font)
    shadow_color  = rgb($base)

    shadow_passes = 2
    shadow_size   = 5
    shadow_boost  = 1.2

    position      = 0, 250
    halign        = center
    valign        = center
}
# }}}

# {{{ Splash
label {
    monitor     =
    text        = cmd[update:9999] hyprctl splash
    font_size   = 11
    font_family = Sans

    color       = rgb($font_splash)

    position    = 0, -30
    halign      = center
    valign      = bottom
}
# }}}
```

### PR DESCRIPTION
**Pull request by bvr-yr**
- pango-parseable `fail_text` with `$FAIL` as pam fail-reason
- `fail_color` to change untagged text color and outer color
- `fail_transition` to configure transition time between `outer` and `fail`
- temporarily resize input-field if fail-message is too long

should fix #97 (https://github.com/hyprwm/hyprlock/issues/97#issuecomment-1981655505)
also accidentally fixed #144, but i'm not sure, maybe it is intended behaviour?
if so, i'll just add check in resize thing to not reshadow if `fade_on_empty = true`

i definitely focked-up somewhere, so double-check plz :heart:

https://github.com/hyprwm/hyprlock/assets/130279855/e09d91ab-80b3-4156-8d8e-775d39e96016

### CODE REVIEW

File: src/renderer/widgets/PasswordInputField.cpp [hunk 1]
```diff
@@ -255,21 +291,27 @@ void CPasswordInputField::updateFailTex() {
...
+            redrawShadow          = true;
         }
         return;
     }
 
     if (!FAIL.has_value() || !placeholder.canGetNewFail)
         return;
 
+    if (placeholder.failText.empty())
+        placeholder.failText = "<span style=\"italic\">" + FAIL.value() + "</span>";
```
Comment (vaxerski) [inline src/renderer/widgets/PasswordInputField.cpp:303]: instead of checking for emptiness, I'd just set this as the default. You can put `$FAIL` in the defaults.

Someone might want to (for some reason) set it to _actually_ empty.

Comment (bvr-yr) [reply src/renderer/widgets/PasswordInputField.cpp]: ye u're right

**Comment by bvr-yr** [comment]
hmm wait.. do actual env vars expand now? i mean not this MR
i believe it was not so some time ago, or was it always like that?

looks odd xD
lul

**Review by vaxerski — APPROVED** [review]
lgtm I guess, wiki mr needed
