### PR TITLE
widgets: add support for specifing size and position options via percentages of output dimensions

### LINKED ISSUE #261: [Feat Req ] Follow Scaling per monitor by default
Maybe I missed something. For QOL, is it possible for the lockscreen layer to follow per monitor scaling by default?
 It's possible to script it and generate compatible per monitor configs, but would be nice to have this by default. Thank you! 

Example
*  mon1 has scaling of 2 while mon2 has 1.  
* hidpi monitors together with non hidpi
* Easy to reproduced for other users 😉

### LINKED ISSUE #446: Text doesn't align correctly
### Regression?

No

### Hyprlock Info and Version

<Enter your hyprlock version here>
<details> <summary>Hyprlock config</summary>

```sh
# BACKGROUND
background {
    color = rgba(25, 20, 20, 1.0)
}

# PLAYER TITLE
label {
    text = Text two long one
    color = rgba(255, 255, 255, 0.8)
    font_size = 12
    text_align = left
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 200, 0
    halign = left/center
    valign = center
}

# PLAYER ARTIST
label {
    text = Text one
    color = rgba(255, 255, 255, 0.8)
    font_size = 10
    text_align = left
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 200, -20
    halign = left/center
    valign = center
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: kamack38-rogstrixg533qs
Release: 6.9.9-arch1-1.2-g14
Version: #1 SMP PREEMPT_DYNAMIC Tue, 16 Jul 2024 05:59:42 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104M [GeForce RTX 3080 Mobile / Max-Q 8GB/16GB] [10de:249c] (rev a1) (prog-if 00 [VGA controller])
05:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://garudalinux.org/"
DOCUMENTATION_URL="https://wiki.garudalinux.org/"
SUPPORT_URL="https://forum.garudalinux.org/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=garudalinux


plugins:
```

</details>

### Description

The text should align to the left and they both should be inline, but they aren't.

### How to reproduce

 halign = left
 
2024-07-29T21:07:38,465196803+02:00

 halign = center

2024-07-29T21:07:18,130660067+02:00

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by PaideiaDilemma**
Adds the ability to specify `size` and `position` options as percentages of the output viewport.
E.g.
```
position = 10%, 10%
size = 10%,5%
```
This is allowed:
```
position = 10%, 10
```
~Question: Do we want to support a `px` suffix to allow more explicitness?~ This is also allowed:
```
position = 10%, 10px
```

To allow users to make layouts that are independent of the output viewport we are missing `label:font_size` and `image:size` (which should be `image:scale` fmpov, but for some reason it was named size...)
But I think it is easier for us to do that in a separate MR.

Part 1 to implement #261
Closes #446 (`halgin=left` and `position = 50%, 0`)

### CODE REVIEW

File: src/config/ConfigDataValues.hpp [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+class ICustomConfigValueData {
+  public:
+    virtual ~ICustomConfigValueData() = 0;
+
+    virtual eConfigValueDataTypes getDataType() = 0;
+
+    virtual std::string           toString() = 0;
+};
+
+class CLayoutValueData : ICustomConfigValueData {
```
Comment (vaxerski) [inline src/config/ConfigDataValues.hpp:21]: public missing?

Comment (PaideiaDilemma) [reply src/config/ConfigDataValues.hpp:21]: it is right below

Comment (vaxerski) [reply src/config/ConfigDataValues.hpp:21]: `public ICustomConfigValueData` sir

**Review by vaxerski — APPROVED** [review]

**Comment by vaxerski** [comment]
wiki mr needed

**Review by vaxerski — APPROVED** [review]
