### PR TITLE
config: add source parsing

### LINKED ISSUE #15: Sourcing file doesn't work.
```
source ~/.config/colors.conf
```
or 
```
source /home/username/colors.conf
```
Variables present in those files are not working in `hyprlock.conf`.
Is it meant to be this way?

And how you implemented different color in the label,(source preview image)?

### PR DESCRIPTION
**Pull request by mauricekraus**
This allows for out**source**ing configs into other files. Fixes #15

### CODE REVIEW

File: src/config/ConfigManager.cpp [hunk 1]
```diff
@@ -132,3 +150,38 @@ std::vector<CConfigManager::SWidgetConfig> CConfigManager::getWidgetConfigs() {
...
+            if (std::filesystem::exists(value)) {
+                Debug::log(WARN, "source= skipping non-file {}", value);
+                continue;
+            }
+
+            Debug::log(ERR, "source= file doesnt exist");
+            return "source file " + value + " doesn't exist!";
+        }
+
+        m_config.parseFile(value.c_str());
```
Comment (vaxerski) [inline src/config/ConfigManager.cpp:182]: you probably should update configCurrentPath no? so that `./lol.conf` called from inslde `./configs/pope.conf` can go to `./configs/lol.conf`

File: src/helpers/MiscFunctions.cpp [hunk 2]
```diff
@@ -0,0 +1,25 @@
+#include "MiscFunctions.hpp"
+
+std::string absolutePath(const std::string& rawpath, const std::string& currentPath) {
+    auto value = rawpath;
+
+    if (value[0] == '~') {
+        static const char* const ENVHOME = getenv("HOME");
+        value.replace(0, 1, std::string(ENVHOME));
+    } else if (value[0] != '/') {
+        auto currentDir = currentPath.substr(0, currentPath.find_last_of('/'));
```
Comment (vaxerski) [inline src/helpers/MiscFunctions.cpp:10]: I hate this. Why not just `canonical( currentPath + rawpath )`

File: src/config/ConfigManager.cpp (hunk 1 above)
Comment (mauricekraus) [reply src/config/ConfigManager.cpp:182]: yep, missed that.

File: src/helpers/MiscFunctions.cpp [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+    // Handling the case where rawpath starts with '~'
+    if (!rawpath.empty() && rawpath[0] == '~') {
+        static const char* const ENVHOME = getenv("HOME");
+        return std::filesystem::path(ENVHOME) / path.relative_path().string().substr(2);
+    }
+    // Handling e.g. ./, ../
+    else if (path.is_relative()) {
+        const std::filesystem::path currentDir = std::filesystem::path(rawcurrentpath).parent_path();
+
+        return std::filesystem::canonical(currentDir / path);
```
Comment (vaxerski) [inline src/helpers/MiscFunctions.cpp:16]: this can throw if the thing couldn't be found. We should return an empty string if tomething throws IMO or return an `std::optional` (I'd prefer `std::expected` but clang will shit itself)

Comment (mauricekraus) [reply src/helpers/MiscFunctions.cpp]: Okay, I've given my best, but I'm a bit confused if some of these error cases can even occur in handleSource. However, due to absolutePaths optionality, I needed to handle it anyway. I tested multiple configurations (invalid paths, etc.), and it should work now

File: src/helpers/MiscFunctions.cpp [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+    // Handling e.g. ./, ../
+    else if (path.is_relative()) {
+        const std::filesystem::path currentDir = std::filesystem::path(rawcurrentpath).parent_path();
+
+        auto finalPath = currentDir / path;
+        if (exists(finalPath))
+            return std::filesystem::canonical(currentDir / path);
+        else
+            return {};
+    } else {
```
Comment (vaxerski) [inline src/helpers/MiscFunctions.cpp:21]: useless else. Just return. all if blocks always return.

**Review by vaxerski — COMMENTED** [review]
rest lgtm, just please slap a clang-format

**Comment by mauricekraus** [comment]
No it should be formatted correctly :sweat_smile:

**Review by vaxerski — APPROVED** [review]
thats better. Thanks!
