### PR TITLE
Nvidia and stuff fixes

### LINKED ISSUE #9: [nvidia] couldnt create eglsurface
```
hyprlock
[LOG]   | got iface: wl_shm v1
[LOG]   | got iface: wl_drm v2
[LOG]   | got iface: zwp_linux_dmabuf_v1 v4
[LOG]   | got iface: wl_compositor v6
[LOG]    > Bound to wl_compositor v6
[LOG]   | got iface: wl_subcompositor v1
[LOG]   | got iface: wl_data_device_manager v3
[LOG]   | got iface: zwlr_export_dmabuf_manager_v1 v1
[LOG]   | got iface: zwlr_data_control_manager_v1 v2
[LOG]   | got iface: zwp_primary_selection_device_manager_v1 v1
[LOG]   | got iface: wp_viewporter v1
[LOG]    > Bound to wp_viewporter v1
[LOG]   | got iface: zwlr_gamma_control_manager_v1 v1
[LOG]   | got iface: zwlr_output_power_manager_v1 v1
[LOG]   | got iface: xdg_wm_base v6
[LOG]   | got iface: wl_seat v9
[LOG]    > Bound to wl_seat v9
[LOG]   | got iface: wp_presentation v1
[LOG]   | got iface: ext_idle_notifier_v1 v1
[LOG]   | got iface: zwlr_layer_shell_v1 v4
[LOG]   | got iface: org_kde_kwin_server_decoration_manager v1
[LOG]   | got iface: zxdg_decoration_manager_v1 v1
[LOG]   | got iface: zwlr_output_manager_v1 v4
[LOG]   | got iface: zwp_keyboard_shortcuts_inhibit_manager_v1 v1
[LOG]   | got iface: zwp_pointer_constraints_v1 v1
[LOG]   | got iface: zwp_relative_pointer_manager_v1 v1
[LOG]   | got iface: zwp_virtual_keyboard_manager_v1 v1
[LOG]   | got iface: zwlr_virtual_pointer_manager_v1 v2
[LOG]   | got iface: zwlr_foreign_toplevel_manager_v1 v3
[LOG]   | got iface: wp_drm_lease_device_v1 v1
[LOG]   | got iface: zwp_tablet_manager_v2 v1
[LOG]   | got iface: zwp_idle_inhibit_manager_v1 v1
[LOG]   | got iface: zxdg_exporter_v1 v1
[LOG]   | got iface: zxdg_importer_v1 v1
[LOG]   | got iface: zxdg_exporter_v2 v1
[LOG]   | got iface: zxdg_importer_v2 v1
[LOG]   | got iface: zwp_pointer_gestures_v1 v3
[LOG]   | got iface: zwp_text_input_manager_v3 v1
[LOG]   | got iface: zwp_input_method_manager_v2 v1
[LOG]   | got iface: xdg_activation_v1 v1
[LOG]   | got iface: ext_session_lock_manager_v1 v1
[LOG]    > Bound to ext_session_lock_manager_v1 v1
[LOG]   | got iface: wp_cursor_shape_manager_v1 v1
[LOG]    > Bound to wp_cursor_shape_manager_v1 v1
[LOG]   | got iface: wp_tearing_control_manager_v1 v1
[LOG]   | got iface: wp_single_pixel_buffer_manager_v1 v1
[LOG]   | got iface: xwayland_shell_v1 v1
[LOG]   | got iface: hyprland_toplevel_export_manager_v1 v2
[LOG]   | got iface: wp_fractional_scale_manager_v1 v1
[LOG]    > Bound to wp_fractional_scale_manager_v1 v1
[LOG]   | got iface: zwp_text_input_manager_v1 v1
[LOG]   | got iface: hyprland_global_shortcuts_manager_v1 v1
[LOG]   | got iface: zwlr_screencopy_manager_v1 v3
[LOG]   | got iface: zxdg_output_manager_v1 v3
[LOG]   | got iface: wl_output v4
[LOG]    > Bound to wl_output v4
[LOG]   | got iface: wl_output v4
[LOG]    > Bound to wl_output v4
[LOG] output 49 make ASUSTek COMPUTER INC model VG27A
[LOG] output 49 name DP-1
[LOG] output 49 description ASUSTek COMPUTER INC VG27A L4LMQS004814 (DP-1)
[LOG] output 50 make ASUSTek COMPUTER INC model VG27A
[LOG] output 50 name DP-2
[LOG] output 50 description ASUSTek COMPUTER INC VG27A L4LMQS004783 (DP-2)
[LOG] Locking session
[LOG] onLockLocked called
[LOG] got fractional 1
[LOG] configure with serial 0
[LOG] configure with serial 1136
ext_session_lock_surface_v1@24: error 1: session lock surface is committed with a null buffer
[LOG] configure with serial 0
[CRITICAL] Couldn't create eglSurface
zsh: segmentation fault (core dumped)  hyprlock
```
nvidia gpu arch linux

### PR DESCRIPTION
**Pull request by vaxerski**
Oopsies and stuff shoutout Simon Ser and ashaffer for help :)

hopefully fixes #9

### CODE REVIEW

File: src/core/LockSurface.cpp [hunk 1]
```diff
@@ -48,12 +48,8 @@ CSessionLockSurface::CSessionLockSurface(COutput* output) : output(output) {
         wp_fractional_scale_v1_add_listener(fractional, &fsListener, this);
         viewport = wp_viewporter_get_viewport(g_pHyprlock->getViewporter(), surface);
         wl_display_roundtrip(g_pHyprlock->getDisplay());
```
Comment (emersion) [inline src/core/LockSurface.cpp:50]: This needs to be dropped as well

**Comment by vaxerski** [comment]
merging as reported working thanks :)
