### PR TITLE
core: add support for composed keys

### LINKED ISSUE #549: Cannot unlock with a Norwegian keyboard layout (accent character)
### Regression?

No

### Hyprlock Info and Version

0.5.0
<details> <summary>Hyprlock config</summary>

```sh
source = $HOME/.config/hypr/hyprlock/colors/catppuccin.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = Maple Mono NF

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/.config/hypr/hyprlock/background
  blur_passes = 0
  color = $base
}

# LAYOUT
label {
  monitor =
  text = Layout: $LAYOUT
  color = $text
  font_size = 25
  font_family = $font
  position = 30, -30
  halign = left
  valign = top
}

# TIME
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.3


flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.11.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Meteor Lake-P [Intel Arc Graphics] [8086:7d55] (rev 08) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

I can't log in when my keyboard layout is Norwegian, it works with a US layout. The issue is probably because there is a `^` in my password, which on a Norwegian keyboard is input by pressing <kbd>Shift</kbd>+<kbd>"</kbd> (to get ^), then <kbd>Space</kbd> to type the character because it is an accent. When I press that key combination only one dot appears (as it should), but I get an authentication error.

I can type the password with a Norwegian keyboard in both SDDM and the terminal, it's just hyprlock that fails. I don't know if there is a way to see which character is typed to help with debugging.

### How to reproduce

Try to unlock with a Norwegian password and a password that contains a `^` character

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by PaideiaDilemma**
Closes #549

### CODE REVIEW

File: src/core/hyprlock.cpp [hunk 1]
```diff
@@ -722,6 +722,15 @@ static void handleKeyboardKeymap(void* data, wl_keyboard* wl_keyboard, uint form
         Debug::log(ERR, "Failed to create xkb state");
         return;
     }
+
+    const auto PCOMOPOSETABLE = xkb_compose_table_new_from_locale(g_pHyprlock->m_pXKBContext, setlocale(LC_CTYPE, NULL), XKB_COMPOSE_COMPILE_NO_FLAGS);
```
Comment (vaxerski) [inline src/core/hyprlock.cpp:726]: `NULL`? Really? In my c++?

**Review by vaxerski — COMMENTED** [review]
rest ok

**Review by vaxerski — APPROVED** [review]
lgtm but issue author needs to test
